In [ ]:
# ====================================================================================================
#                                E-Commerce Data Analysis Projec
#  ===================================================================================================

In [ ]:
# ------------------
# 1. Introduction
# -----------------

In [ ]:
# This project analyzes an e-commerce dataset using Python to uncover business insights related to customer behavior, product performance, and sales trends.

# The dataset includes multiple tables such as users, products, orders, order items, reviews, and events, representing the full workflow of an online shopping platform.

# The goal of this analysis is to:
# - Understand revenue and sales performance
# - Identify top products and categories
# - Analyze customer behavior and segmentation
# - Study trends over time
# - Perform funnel analysis (view → cart → purchase)

# This project demonstrates how data can be used to support business decisions and improve overall performance.

In [ ]:
# ----------------------------------
#       2. Data Loading
# ----------------------------------

In [1]:
import pandas as pd

users = pd.read_csv(r"C:\Users\boyal\OneDrive\Python_Data_Analytics_Portfolio\Project_1_Ecommerce_Analysis\01_Data\users.csv")
reviews = pd.read_csv(r"C:\Users\boyal\OneDrive\Python_Data_Analytics_Portfolio\Project_1_Ecommerce_Analysis\01_Data\reviews.csv")
products = pd.read_csv(r"C:\Users\boyal\OneDrive\Python_Data_Analytics_Portfolio\Project_1_Ecommerce_Analysis\01_Data\products.csv")
orders = pd.read_csv(r"C:\Users\boyal\OneDrive\Python_Data_Analytics_Portfolio\Project_1_Ecommerce_Analysis\01_Data\orders.csv")
order_items = pd.read_csv(r"C:\Users\boyal\OneDrive\Python_Data_Analytics_Portfolio\Project_1_Ecommerce_Analysis\01_Data\order_items.csv")
events = pd.read_csv(r"C:\Users\boyal\OneDrive\Python_Data_Analytics_Portfolio\Project_1_Ecommerce_Analysis\01_Data\events.csv")

In [ ]:
# -------------------------------------
#       3. Data Understanding
# -------------------------------------

In [2]:
users.shape

(10000, 6)

In [3]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      10000 non-null  object
 1   name         10000 non-null  object
 2   email        10000 non-null  object
 3   gender       10000 non-null  object
 4   city         10000 non-null  object
 5   signup_date  10000 non-null  object
dtypes: object(6)
memory usage: 468.9+ KB

In [6]:
users.describe()

,user_id,name,email,gender,city,signup_date
count,10000,10000,10000,10000,10000,10000
unique,10000,9340,10000,3,7755,684
top,U009984,Michael Jones,watkinscharles@example.net,Other,North Michael,12-09-2024
freq,1,6,1,3419,13,27

In [7]:
users.head()

,user_id,name,email,gender,city,signup_date
0,U000001,Angel Hill,donaldgarcia@example.net,Other,New Roberttown,13-03-2025
1,U000002,Jesse Guzman,jennifermiles@example.com,Male,South Bridget,05-03-2024
2,U000003,Adam Shaffer,jpeterson@example.org,Male,Curtisfurt,07-07-2025
3,U000004,Melanie Munoz,blairamanda@example.com,Other,New Kellystad,07-03-2024
4,U000005,Janet Williams,kendragalloway@example.org,Female,South Joshuastad,29-01-2025

In [8]:
users.isnull().sum()

user_id        0
name           0
email          0
gender         0
city           0
signup_date    0
dtype: int64

In [9]:
users.columns

Index(['user_id', 'name', 'email', 'gender', 'city', 'signup_date'], dtype='object')

In [10]:
reviews.shape

(15000, 7)

In [11]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    15000 non-null  object
 1   order_id     15000 non-null  object
 2   product_id   15000 non-null  object
 3   user_id      15000 non-null  object
 4   rating       15000 non-null  int64
 5   review_text  15000 non-null  object
 6   review_date  15000 non-null  object
dtypes: int64(1), object(6)
memory usage: 820.4+ KB

In [12]:
reviews.describe()

             rating
count  15000.000000
mean       3.544667
std        1.103669
min        1.000000
25%        3.000000
50%        4.000000
75%        4.000000
max        5.000000

In [13]:
reviews.head()

,review_id,order_id,product_id,user_id,rating,review_text,review_date
0,R00000528,O00000237,P001326,U001094,2,Color was different from images.,2025-10-14T12:03:56.749446
1,R00005792,O00002627,P000329,U001858,4,Highly recommend this brand.,2024-10-09T08:04:50.171793
2,R00036604,O00016798,P001160,U008109,4,Highly recommend this brand.,2024-06-03T05:11:16.787214
3,R00040163,O00018414,P001427,U006835,5,Highly recommend this brand.,2024-02-12T06:41:50.215810
4,R00031127,O00014300,P001639,U007148,3,Item arrived damaged.,2025-01-20T05:32:09.398860

In [19]:
reviews.isnull().sum()

review_id      0
order_id       0
product_id     0
user_id        0
rating         0
review_text    0
review_date    0
dtype: int64

In [15]:
events.shape

(80000, 5)

In [16]:
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_id         80000 non-null  object
 1   user_id          80000 non-null  object
 2   product_id       80000 non-null  object
 3   event_type       80000 non-null  object
 4   event_timestamp  80000 non-null  object
dtypes: object(5)
memory usage: 3.1+ MB

In [17]:
events.describe()

         event_id  user_id product_id event_type             event_timestamp
count       80000    80000      80000      80000                       80000
unique      80000     9995       2000          4                       80000
top     E00079984  U006046    P001112       view  2024-05-14T20:17:41.446172
freq            1       23         63      56013                           1

In [18]:
events.head()

    event_id  user_id product_id event_type             event_timestamp
0  E00000001  U009798    P001393       cart  2025-07-08T14:28:55.893919
1  E00000002  U005881    P000669       view  2025-10-19T23:00:44.067982
2  E00000003  U006348    P001404       view  2025-05-09T07:02:42.256662
3  E00000004  U002664    P000400       cart  2025-07-19T22:47:07.019634
4  E00000005  U005776    P000392       view  2024-10-24T10:20:33.602165

In [20]:
events.isna().sum()

event_id           0
user_id            0
product_id         0
event_type         0
event_timestamp    0
dtype: int64

In [22]:
products.shape

(2000, 6)

In [23]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    2000 non-null   object
 1   product_name  2000 non-null   object
 2   category      2000 non-null   object
 3   brand         2000 non-null   object
 4   price         2000 non-null   float64
 5   rating        2000 non-null   float64
dtypes: float64(2), object(4)
memory usage: 93.9+ KB

In [24]:
products.head()

  product_id     product_name        category    brand   price  rating
0    P000001         Astra Be        Clothing    Astra  157.89    4.08
1    P000002  NeoTech Someone       Groceries  NeoTech   21.46    3.87
2    P000003     Acme Discuss          Sports     Acme  265.37    3.46
3    P000004     Nimbus South     Electronics   Nimbus  541.41    4.14
4    P000005    Astra Capital  Home & Kitchen    Astra  198.00    3.97

In [25]:
products.isna().sum()

product_id      0
product_name    0
category        0
brand           0
price           0
rating          0
dtype: int64

In [26]:
orders.shape

(20000, 5)

In [27]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      20000 non-null  object
 1   user_id       20000 non-null  object
 2   order_date    20000 non-null  object
 3   order_status  20000 non-null  object
 4   total_amount  20000 non-null  float64
dtypes: float64(1), object(4)
memory usage: 781.4+ KB

In [28]:
orders.isna().sum()

order_id        0
user_id         0
order_date      0
order_status    0
total_amount    0
dtype: int64

In [29]:
orders.head()

    order_id  user_id                  order_date order_status  total_amount
0  O00000001  U009310  2025-09-09T14:52:37.292731   processing        689.66
1  O00000002  U003247  2025-04-15T01:18:27.193404    completed       1666.85
2  O00000003  U007252  2025-04-27T15:37:48.008624   processing        665.06
3  O00000004  U008986  2025-10-04T20:35:22.204857    cancelled        689.50
4  O00000005  U008537  2024-11-13T08:15:18.498252    cancelled        860.50

In [30]:
order_items.shape

(43525, 7)

In [31]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43525 entries, 0 to 43524
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  43525 non-null  object
 1   order_id       43525 non-null  object
 2   product_id     43525 non-null  object
 3   user_id        43525 non-null  object
 4   quantity       43525 non-null  int64
 5   item_price     43525 non-null  float64
 6   item_total     43525 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 2.3+ MB

In [32]:
order_items.head()

,order_item_id,order_id,product_id,user_id,quantity,item_price,item_total
0,I00000001,O00000001,P001758,U009310,2,8.07,16.14
1,I00000002,O00000001,P001119,U009310,1,74.08,74.08
2,I00000003,O00000001,P001794,U009310,1,576.97,576.97
3,I00000004,O00000001,P001038,U009310,1,22.47,22.47
4,I00000005,O00000002,P000859,U003247,1,422.22,422.22